# config/transformation_config.yaml

logs_move:
  table: logs_move
  group_by: player_id
  aggregations:
    - column: id
      agg: count
      alias: move_count

logs_attack:
  table: logs_attack
  group_by: player_id
  aggregations:
    - column: id
      agg: count
      alias: attack_count
    - column: damage
      agg: sum
      alias: total_damage

logs_heal:
  table: logs_heal
  group_by: player_id
  aggregations:
    - column: id
      agg: count
      alias: heal_count
    - column: heal_amount
      agg: sum
      alias: total_heal
